apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    certificate-authority: ./ca.crt
    server: https://kubernetes.api.server:6443
users:
- name: my-user
  user:
    client-certificate: ./user.crt
    client-key: ./user.key
contexts:
- name: my-context
  context:
    cluster: my-cluster
    user: my-user
current-context: my-context
